microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/cstariomock
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.rtd.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 30 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"

  keyvault:
    name: "cstar-u-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
